[package]
name = "stable-enum"
version = "1.0.0"
description = "MR Research AG enumeration lib implemented in stable memory regions"
repository = "https://github.com/bittoko/stable-enum"
keywords = [ "set", "bijective", "map", "lookup", "key", "enumeration" ]
license = "Apache-2.0"

[dependencies]
base = "0.10.4"