[package]
name = "stable-enum"
version = "1.0.0"
description = "Enumerations implemented in stable memory regions"
repository = "https://github.com/bittoko/stable-enum"
keywords = [
  "enumeration",
  "stable",
  "memory",
  "region",
  "lookup",
  "enum"
]
license = "Apache-2.0"

[dependencies]
base = "0.10.4"
stable-buffer = "1.0.1"